-- General settings
require("options")
require("keymaps")
require("autocmds")

-- Lazy
require("plugins")

-- Plugin configurations 
require("plugins.alpha")
require("plugins.colorscheme")
require("plugins.nvim-tree")
require("plugins.mason")
require("plugins.copilot")
require("plugins.rose-pine")
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins._telescope")
require("plugins.completions")
require("plugins.bufferline")
require("plugins.which-key")
require("plugins.lspconfig")
require("plugins.undotree")
require("plugins.gitsigns")
require("plugins.indent_blankline")
require("plugins.clangd_extensions")
-- require("plugins.navigator")
-- require("plugins.notify")
