vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Explore)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set("n", "<leader>d", [[:g/^$/d]])
vim.keymap.set({"n", "v"}, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
vim.keymap.set("n", "<C-b>", "<cmd> !clear && time cargo run %<CR>", { silent = false})
vim.keymap.set("n", "<C-b>", "<cmd> !clear && time swiftc % && ./main<CR>", { silent = false})
vim.keymap.set("n", "<C-n>", "<cmd> !clear && time python%<CR>", { silent = false})
vim.keymap.set("n", "<C-c>", "<cmd> !clear && time gcc % && ./a.out<CR>", { silent = false})
vim.keymap.set("n", "<C-g>", ":NvimTreeToggle%:p:h<CR>")
vim.keymap.set("n", "<C-i>", ":Telescope keymaps <CR>")
vim.keymap.set("n", "<leader>md", ":MarkdownPreview<CR>")
vim.keymap.set("n", "<leader>mdt", ":MarkdownPreviewToggle<CR>")
vim.keymap.set("n", "<leader>mds", ":MarkdownPreviewStop<CR>")

-- vim.keymap.set("n", "<C-q>", ":set colorcolumn=80<CR>")
--vim.keymap.set("n", "<C-w>", ":set colorcolumn=0<CR>")
